# docker-compose.yml
version: '3'

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.load_balancer
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=1
    ports:
      - "5001:5000"

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=2
    ports:
      - "5002:5000"

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=3
    ports:
      - "5003:5000"
